routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->check()) {
        return redirect('/p2p?crypto_id=1&sum_currency=&currency_id=155&payment_type_id=&country_id=206&city_id=');
    }

    return view('welcome')->with('viewport', true);
});

Route::view('about-company', 'about-company');

Route::view('agreement', 'agreement');

Route::view('nocommission', 'nocommission');

Route::view('affiliate-program', 'affiliate-program');

Route::get('commissions', 'StaticController@commission');

Route::view('contacts', 'contacts');

Route::view('help', 'help');

Route::view('news', 'news');

Route::view('remote-work', 'remote-work');

Route::view('representatives', 'representatives');

Route::view('security', 'security');

Route::redirect('home', '/p2p')->name('home');

Route::view('exchange','exchange');
Route::view('typeofrisk','typeofrisk');
Route::view('wallet','wallet');
Route::view('personalbonuses','personalbonusesforguest');

Route::get('p2p', 'PagesController@buy');
Route::get('cryptoexchange', 'PagesController@trade');
Route::get('cryptosell', 'PagesController@sell');
Route::get('p2p/{type}', 'PagesController@paginate');

Route::get('profile/{login}', 'ProfileController@show');
Route::get('profile/{login}/adverts', 'ProfileController@adverts');

Route::get('countries/{country}', 'CountryController@show');
Route::get('countries/{country}/cities', 'CountryController@cities');

Route::get('user/activation/{user_activation}', 'ActivationController@handle')->name('user.activate');

Route::group(['middleware' => 'guest'], function() {
    Auth::routes();

    Route::get('2fa/validate', 'Auth\LoginController@showConfirmationLogin');
    Route::post('2fa/validate', ['middleware' => 'throttle:5', 'uses' => 'Auth\LoginController@confirmationLogin']);
});

Route::get('publications/create', 'AdvertController@create');
Route::get('publications/{advert}', 'AdvertController@show');

Route::group(['middleware' => ['auth', 'activity']], function() {
    Route::get('logout', 'Auth\LoginController@logout');

    Route::patch('change-visibility/{advert}', 'AdvertController@changeVisibility');

    Route::post('is-address-has-a-user', 'AddressController@isAddressHasAUser');

    Route::get('send-email-confirmation', 'EmailController@confirm');

    Route::patch('read-operations', 'OperationController@update');

    Route::patch('read-deal-history', 'DealHistoryController@update');

    Route::patch('read-partner-history', 'PartnerController@read_partner_history');

    Route::patch('avatar', 'AvatarController@update');

    Route::post('rate', 'RateController@calculation');

    Route::get('my-wallet', 'OperationController@index');

    Route::view('general-information', 'general-information');
    Route::patch('general-information', 'SettingController@update_general');

    Route::get('my-security', 'SettingController@security');
    Route::patch('my-security', 'SettingController@update_security');

    Route::view('verification', 'verification');
    Route::post('verification', 'VerificationController@index');

    Route::get('2fa/enable', 'GoogleFAController@enable');
    Route::post('2fa/enable', 'GoogleFAController@confirm_enable');
    Route::get('2fa/disable', 'GoogleFAController@disable');
    Route::post('2fa/disable', 'GoogleFAController@confirm_disable');

    Route::patch('change_email', 'SettingController@change_email');
    Route::patch('confirm_change_email', 'SettingController@confirm_change_email');
    Route::patch('change_password', 'SettingController@change_password');

    Route::get('publications', 'AdvertController@index');
    Route::post('publications', 'AdvertController@store');
    Route::post('validate-advert-copy', 'AdvertController@validateAdvertCopy');
    Route::get('publications/{advert}/edit', 'AdvertController@edit');
    Route::patch('publications/{advert}', 'AdvertController@update');
    Route::delete('publications/{advert}', 'AdvertController@destroy');

    Route::get('deals', 'DealController@index');
    Route::post('deals', 'DealController@store');
    Route::get('deals/{deal}', 'DealController@show');
    Route::patch('deals/{deal}', 'DealController@update');

    Route::get('send-confirmation-code/{deal}', 'DealController@send_confirmation_code');


    Route::post('messages', 'MessageController@store');
    Route::get('messages/{deal}', 'MessageController@show');

    Route::post('withdrawals/{crypto_currency}', 'WithdrawalController@store');
    Route::get('withdrawals/{crypto_currency}', 'WithdrawalController@show');

    Route::get('replenishment/{crypto_currency}', 'AddressController@index');

    Route::get('my-partners', 'PartnerController@index');	
    Route::get('transfer-income/{crypto_currency}', 'PartnerController@transfer_income');

    Route::get('user/{user}/auth','ProfileController@auth');

    Route::get('refresh-notifications', 'ProfileController@refreshNotifications');
	
	Route::get('mybonuses', 'BonusesController@index');
});

Route::group(['middleware' => 'admin', 'namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::get('users','UserController@index');
    Route::get('achievements','AchievementController@index');
    Route::get('addresses','AddressController@index');
    Route::get('countries_and_currencies','CountryController@index');
    Route::get('payment_types_and_risks','PaymentTypeController@index');
    Route::get('operations','OperationController@index');
    Route::get('replenishment','OperationController@create');
    Route::get('banks','BankController@index');
    Route::get('withdrawals', 'WithdrawalController@index');
    Route::get('additional_crypto_currencies', 'AdditionalCryptoCurrencyController@index');
    Route::get('commissions', 'CryptoCurrencyController@index');
    Route::get('profit', 'ProfitController@index');
    Route::get('deals', 'DealController@index');
    Route::get('verification', 'VerificationController@index');
    Route::get('notices','NoticeController@index');

    Route::get('users/{user}','UserController@show');
    Route::get('users/{user}/auth','UserController@auth');
    Route::patch('users/{user}','UserController@update');
    Route::delete('users/{user}','UserController@destroy');

    Route::post('achievements', 'AchievementController@store');
    Route::get('achievements/{achievement}', 'AchievementController@show');
    Route::post('achievements/{achievement}','AchievementController@update');
    Route::delete('achievements/{achievement}','AchievementController@destroy');

    Route::post('addresses','AddressController@store');
    Route::get('send-confirmation-code', 'AddressController@sendConfirmationCode');

    Route::post('countries','CountryController@store');
    Route::get('countries/{country}','CountryController@show');
    Route::patch('countries/{country}','CountryController@update');
    Route::delete('countries/{country}','CountryController@destroy');

    Route::post('currencies','CurrencyController@store');
    Route::patch('currencies/{currency}','CurrencyController@update');
    Route::delete('currencies/{currency}','CurrencyController@destroy');

    Route::post('operations','OperationController@store');

    Route::post('banks','BankController@store');
    Route::get('banks/{bank}','BankController@show');
    Route::patch('banks/{bank}','BankController@update');
    Route::delete('banks/{bank}','BankController@destroy');

    Route::post('risks','RiskController@store');
    Route::delete('risks/{risk}','RiskController@destroy');

    Route::post('payment_types','PaymentTypeController@store');
    Route::get('payment_types/{payment_type}','PaymentTypeController@show');
    Route::patch('payment_types/{payment_type}','PaymentTypeController@update');
    Route::delete('payment_types/{payment_type}','PaymentTypeController@destroy');

    Route::delete('withdrawals/{withdrawal}', 'WithdrawalController@destroy');
    Route::patch('withdrawals/{withdrawal}', 'WithdrawalController@update');

    Route::post('additional_crypto_currencies', 'AdditionalCryptoCurrencyController@store');
    Route::delete('additional_crypto_currencies/{additional_crypto_currency}', 'AdditionalCryptoCurrencyController@destroy');

    Route::get('commissions/{crypto_currency}', 'CryptoCurrencyController@show');
    Route::patch('commissions/{crypto_currency}','CryptoCurrencyController@update');

    Route::patch('deals/{deal}', 'DealController@changeStatus');
    Route::get('deals/{deal}/auth', 'DealController@auth');

    Route::post('notices','NoticeController@store');
    Route::get('notices/{notice}','NoticeController@show');
    Route::patch('notices/{notice}','NoticeController@update');
    Route::delete('notices/{notice}','NoticeController@destroy');
});

app/Models/Achievement.php
<?php

namespace App\Models;

use Storage;

class Achievement extends Model
{
    public $timestamps = false;

    public function getImageAttribute($value)
    {
        if (is_null($value)) {
            return Storage::url('public/achievements/' . $this->id . '.png');
        }

        return url($value);
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('created_at');
    }

    public function delete()
    {
        $this->users()->detach();

        return parent::delete();
    }
}

resources/views/about-company.blade.php
@extends('layouts.app')

@title('О компании')

@className('main_infopage')

@section('content')

	<div class="content">
		<div class="infopage infopage_about-company">
			<div class="infopage__title-wrap">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<h1 class="infopage-title">О компании</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="infopage__content">
						<div class="infopage-block infopage-block_about-company">
							<div class="infopage-block__text">
								<div class="infopage-block__logo"><img src="/images/content/logo_page_about.png" alt="Логотип"></div>
								<p>CRYPTOLIDE - Первый и единственный международный сервис, который объединил систему P2P сделок и защищённый <br>кошелёк, создав при этом, наверное, самую удобную площадку для покупки, продажи и обмена криптовалюты.</p>
								<p>Работа над проектом началась в 2015 году. Alpha запуск платформы состоялся в мае 2017 года, и в этом же месяце название компании было изменено на CRYPTOLIDE. После этого в августе был опубликован анонс официального релиза сервиса. В октябре 2017 года состоялся Beta запуск платформы, который позволял всем желающим присоединится к тестированию. В течение финального тестового периода, в котором приняло участие около 500 пользователей, были исправлены мелкие ошибки, а также учтены все просьбы и пожелания будущих клиентов. В марте 2018 года состоялся официальный запуск сервиса Криптолайд. В общей сложности, нам потребовалась около 3-х лет, чтобы предоставить вам действительно выгодный, удобный и современный сервис, который хотелось бы рекомендовать друзьям и знакомым.</p>
								<p>Концепция работы сервиса состоит из 5 важных факторов, которых постоянно и обязательно придерживается руководство, ведь они в сумме образуют именно ту идеальную систему, над разработкой которой команда CRYPTOLIDE так долго трудилась.</p>
								<p>Обязательные и неизменные факторы, которые заложены в основу CRYPTOLIDE:</p>
							</div>
							<div class="factors">
								<div class="factors__item clearfix">
									<div class="factors__left">
										<div class="factors__img"><img src="/images/content/factors_img1.png" alt="factors_1"></div>
									</div>
									<div class="factors__right">
										<h3 class="factors__title">Безопасность</h3>
										<div class="factors__text">Безопасность ваших аккаунтов и средств - основа и фундамент нашей компании, на котором построены все остальные функции. Мы придерживаемся мнения, что мощная защита - наиболее важная задача для любой уважающей себя компании. О том, какие алгоритмы защиты мы используем, подробно описано <a href="/security">здесь.</a></div>
									</div>
								</div>
								<div class="factors__item clearfix">
									<div class="factors__left">
										<div class="factors__img"><img src="/images/content/factors_img2.png" alt="factors_2"></div>
									</div>
									<div class="factors__right">
										<h3 class="factors__title">Идеология</h3>
										<div class="factors__text">Наша позиция очень проста: интересы сервиса всегда будут выше, чем вопросы заработка. Используя CRYPTOLIDE, вы всегда можете быть уверенными, что для каждого пользователя предоставляются действительно наиболее выгодные и интересные условия. <a href="/commissions">Проверьте</a>, и убедись в этом лично.</div>
									</div>
								</div>
								<div class="factors__item clearfix">
									<div class="factors__left">
										<div class="factors__img"><img src="/images/content/factors_img3.png" alt="factors_3"></div>
									</div>
									<div class="factors__right">
										<h3 class="factors__title">Искренняя любовь к клиентам</h3>
										<div class="factors__text">Наша цель - сделать все для того, чтобы каждый пользователь, не зависимо от оборота его средств и рейтинга, остался довольным и от всей души рекомендовал CRYPTOLIDE друзьям и знакомым. Мы отобрали наилучших сотрудников, которые разделяют наши взгляды, и круглосуточно будут готовы <a href="/contacts">ответить</a> на ваши вопросы.</div>
									</div>
								</div>
								<div class="factors__item clearfix">
									<div class="factors__left">
										<div class="factors__img"><img src="/images/content/factors_img4.png" alt="factors_4"></div>
									</div>
									<div class="factors__right">
										<h3 class="factors__title">Инновационность</h3>
										<div class="factors__text">Мы не из тех, кто, однажды создав продукт годами его не дорабатывает. Каждый день в мире происходят важные открытия, появляются новые способы взлома и защиты, разрабатываются алгоритмы, упрощаются задачи. Мы внимательно следим за всеми инновациями и постоянно улучшаем наш сервис.</div>
									</div>
								</div>
								<div class="factors__item clearfix">
									<div class="factors__left">
										<div class="factors__img"><img src="/images/content/factors_img5.png" alt="factors_5"></div>
									</div>
									<div class="factors__right">
										<h3 class="factors__title">Благодарность</h3>
										<div class="factors__text">Каждый пользователь, который любым образом способствовал развитию сервиса - будет вознаграждён. Для желающих продвигать сервис стандартными инструментами мы уже разработали уникальную <a href="/affiliate-program">партнёрскую программу</a>, в которой не зарегистрированные пользователи ищут и привлекают партнёров, а, наоборот, будущие пользователи сами ищут партнёрские ссылки, чтобы по них зарегистрироваться. Не стесняйтесь проявлять инициативу, ведь даже когда вы найдёте ошибку в тексте - вас уже ждет награда. Для профессионалов, отлично разбирающихся в криптовалютной тематике или просто настойчивых любителей, которые постоянно стремятся любыми возможными способами улучшить сервис - команда CRYPTOLIDE в виде награды приготовила пожизненное присвоение одного из <a href="/representatives">постоянных статусов</a>, или обсуждаемый размер прямого денежного перевода на ваши реквизиты. С нетерпением ждём любых ваших замечания и предложений.</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/active-deals.blade.php
@extends('layouts.app')

@title('Бизнес профиль пользователя ' . $user->login)

@className('main_business-profile')

@section('content')
<div class="content">
  <div class="title-wrap title-wrap_business-profile">
    <div class="container">
      <div class="row">
        <h1 class="page-title title-wrap__title">Бизнес профиль пользователя <span style="color: #59ba41;">{{ $user->login }}</span></h1>
        <a href="/" class="btn-back title-wrap__back">назад</a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="user-profile user-profile_business">
          <div class="user-profile__photo"><img src="{{ $user->image }}" alt=""></div>
          <div class="user-profile__info user-profile__info_{{ $user->is_online ? 'online' : 'offline' }}">
            @if ($user->show_name)
            <div class="user-profile__realname"><span class="user-profile__realname-inner">{{ $user->last_name . ' ' . $user->name . ' ' . $user->middle_name }}</span></div>
            @endif
            <a href="#" class="user-profile__name">{{ $user->login }}</a>
            <div class="user-profile__rating">{{ $user->rating }}</div>                          

            @foreach($user->achievements as $achievement)
            <img src="{{ $achievement->image }}" alt="" class="user-profile__ok">
            @endforeach
          </div>
        </div>
        @if (!auth()->check())
        <div class="get-gift get-gift_business">
          <a href="/?r={{ $user->id }}" class="btn-green2 btn-green2_get-gift">Получить подарок от {{ $user->login }}</a>
        </div>
        @endif
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <ul class="settings-tabs settings-tabs_business-profile settings-tabs_userinfo">
          <li class="settings-tabs__item"><a href="/profile/{{ $user->login }}" class="settings-tabs__link">ИНФОРМАЦИЯ О ПОЛЬЗОВАТЕЛЕ</a></li>
          <li class="settings-tabs__item settings-tabs__item_active"><a href="/profile/{{ $user->login }}/adverts" class="settings-tabs__link">АКТИВНЫЕ ОБЪЯВЛЕНИЯ ПОЛЬЗОВАТЕЛЯ <span class="deals-number">{{ $user->adverts()->where('status', 'active')->count() }}</span></a></li>
        </ul>
        @forelse($catalog as $name => $adverts)
        <div class="action-table-wrapper action-table-wrapper_business-profile">
          <h2 class="action-table-wrapper__title">
            {{ $name }}
          </h2>
          <div class="table-responsive">
            <table class="action-table">
              <thead class="action-table__thead">
                <tr class="action-table__tr">
                  <td class="action-table__seller">Продавец</td>
                  <td class="action-table__buy-with">
                    {{ explode(' ', $name)[0] }} BTC с помощью
                  </td>
                  <td class="action-table__price">Цена за 1 BTC</td>
                  <td class="action-table__sum">Мин. - макс. сумма</td>
                  <td class="action-table__action-type">Тип действия</td>
                </tr>
              </thead>
              <tbody class="action-table__tbody">
                @foreach($adverts as $advert)
                <tr class="action-table__tr">
                  <td class="action-table__seller">
                    <div class="action-table__seller-photo"><img src="{{ $advert->user->image }}" alt=""></div>
                    <div class="action-table__seller-info action-table__seller-info_{{ $advert->user->is_online ? 'online' : 'offline' }}">
                      <div class="action-table__seller-info-block_left">
                        <a href="/profile/{{ $advert->user->login }}" class="action-table__seller-name">{{ $advert->user->login }}</a>
                        <div class="action-table__seller-status" data-toggle="tooltip" title="{{ $advert->user->is_online ? 'Сейчас онлайн' : 'Заходил ' . $advert->user->last_activity_format }}"></div>
                      </div>

                      <div class="action-table__seller-rating">
                        {{ $advert->user->rating }}
                        <span class="action-table__seller-icons">
                          @if ($advert->user->verified)
                          <span data-toggle="tooltip" title="Пройдена полная верификация личности">
                            <img src="/images/icons/ok.png" alt="OK">
                          </span>
                          @endif

                          @foreach($user->achievements as $achievement)
                          <span data-toggle="tooltip" title="Верифицирован телефонный номер">
                            <img src="{{ $achievement->image }}" alt="" class="user-profile__ok">
                          </span>
                          @endforeach
                        </span>
                      </div>
                    </div>
                  </td>
                  <td class="action-table__buy-with">
                    <a href="#" class="action-table__link">
                      @if ($advert->type == 'sell_online' || $advert->type == 'buy_online')
                      {{ $advert->payment_type_id == 2 ? $advert->banks : '' }}
                      @endif

                      @if ($advert->type == 'sell_for_cash' || $advert->type == 'buy_for_cash')
                      {{ $advert->city->name }}
                      @endif

                      @if ($advert->type == 'trade')
                      {{ $advert->currency_name }}
                      @endif
                    </a>
                  </td>
                  <td class="action-table__price">{{ $advert->rate() }}</td>
                  <td class="action-table__sum">{{ $advert->minCurrency() }} - {{ $advert->sumCurrency() }} {{ $advert->currency_name }}</td>
                  <td class="action-table__action-type">
                    <a href="/publications/{{ $advert->id }}" class="btn-lime">
                      @if ($advert->short_type == 'buy')
                      Продать
                      @elseif ($advert->short_type == 'sell')
                      Купить
                      @elseif ($advert->short_type == 'trade')
                      Обменять
                      @endif
                    </a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        @empty
        <div class="action-table-wrapper">
          <table class="action-table">
            <tbody class="action-table__tbody">
              <tr class="action-table__empty">
                <td colspan="5">Объявления отсутствуют.</td>
              </tr>
            </tbody>
          </table>
        </div>
        @endforelse

      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script>
  $('.jqstyler').styler({
    onFormStyled: function () {
      $('.jq-selectbox').each(function (index, el) {
        var bgImg = $(this).find('.jq-selectbox__dropdown ul li.selected').css('background-image');
        $(this).find('.jq-selectbox__select-text').css('background-image', bgImg);
      });
    },
    onSelectClosed: function () {
      var bgImg = $(this).find('.jq-selectbox__dropdown ul li.selected').css('background-image');
      $(this).find('.jq-selectbox__select-text').css('background-image', bgImg);
    }
  });
</script>
@endsection

resources/views/personalbonuses.blade.php
@extends('layouts.app')

@title('Персональные бонусы')

@className('main')

@section('content')
	<div class="content">
		<div class="infopage infopage_bonuses">
			<div class="title-wrap title-wrap_mybonuses">
		    <div class="container">
		      <div class="row">
		        <h1 class="page-title title-wrap__title">Мои акции и бонусы</h1>
		        <a href="/" class="btn-back title-wrap__back">назад</a>
		      </div>
		    </div>
		  </div>
			<div class="container">
				<div class="row">
					<div class="bonuses bonuses_page-mybonuses">
						<h2 class="bonuses__title">Благодаря системе аналитики действий, мы подберём и бесплатно подарим вам именно те бонусы и акционные <br>предложения, которые действительно будут вам полезны.</h2>
						<div class="bonuses__text"><p>К примеру, если вы любите торговать - система подберёт для вас бонусы, акции или расширенные инструменты, которые значительно улучшат торговлю и увеличат взаимодействие с другими участниками сервиса. Для пользователей, которые занимаются привлечением партнёров в команду, умный алгоритм сформирует временное подарочное увеличение партнёрской ставки, сертификаты на зачисление в команду тех пользователей, которые были зарегистрированы без пригласителя или другие интересные бонусы.</p></div>
					</div>
					<div class="shares-blocks">
						<h2 class="shares-blocks__title"><img src="{{ auth()->user()->image }}" alt="Фотография" class="img-small shares-blocks__avatar"> <span class="shares-blocks__username">{{ auth()->user()->login }},</span> на основе анализа ваших действий мы дарим вам:</h2>
						<div class="shares-blocks__blocks">
							<div class="shares-block">
								<div class="shares-block__left">
									<div class="shares-block__type">Акция</div>
									<div class="shares-block__number">#1</div>
								</div>
								<div class="shares-block__right">
									<h2 class="shares-block__title">Дополнительное отключение комиссии на все операции в торговой платформе</h2>
									<div class="shares-block__text">
										<p>Каждый раз, когда объем ваших сделок суммарно будет достигать 0.50000000 BTC - отключение комиссии будет продлеваться на +7 календарных дней от последней установленной даты. К примеру, за суммарный объем в 5 BTC вы получите дополнительное отключение комиссии на 70 календарных дней после окончания общего акционного периода. Тип завершенных сделок не имеет значения. Любые ограничения отсутствуют. Текущая дата окончания вашего персонального акционного периода указана в выпадающем меню профиля.</p>
									</div>
									<div class="shares-block__validity">Акция действует до: 1.08.2018</div>
								</div>
							</div>
							<div class="shares-block shares-block_bonus">
								<div class="shares-block__left">
									<div class="shares-block__type">Бонус</div>
									<div class="shares-block__number">#2</div>
								</div>
								<div class="shares-block__right">
									<h2 class="shares-block__title">Отключение комиссии на 5 дней календарных дней</h2>
									<div class="shares-block__text">
										<p>В любое удобное для вас время - активируйте этот бонус и мгновенно получите отключение комиссии на все операции в торговой платформе сроком на 5 календарных дней. Бонус можно активировать в любой момент, когда значение комиссии будет больше нуля. Текущая дата окончания вашего персонального акционного периода указана в выпадающем меню профиля.</p>
									</div>
									<div class="shares-block__validity">Срок действия бонуса: неограниченно</div>
									<div class="shares-block__activate-offer">
										<div class="btn-activate">Активировать бонус #2</div>
									</div>
								</div>
							</div>
							<div class="shares-block">
								<div class="shares-block__left">
									<div class="shares-block__type">Акция</div>
									<div class="shares-block__number">#3</div>
								</div>
								<div class="shares-block__right">
									<h2 class="shares-block__title">+2 месяца отсутствия комиссии на любые операции с вашими партнёрами</h2>
									<div class="shares-block__text">
										<p>Все партнёры, которые зарегистрируются по вашей ссылке до 1 августа 2018 года, дополнительно получат +2 месяца полного отсутствия комиссий на все типы операций, которые будут проводиться с вами. Таким образом, вы можете пригласить в сервис своих друзей, знакомых или партнёров по бизнесу, и быть уверенными в том, что в любое удобное время с момента их регистрации и на протяжении 8 месяцев (6 месяцев по умолчанию + 2 дополнительных месяца в рамках этой акции), вы сможете заключить с ними неограниченное количество надёжно защищенных сделок, которые не будут облагаться комиссией. </p>
									</div>
									<div class="shares-block__validity">Акция действует до: 1.08.2018</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
@endsection

resources/views/personalbonusesforguest.blade.php
@extends('layouts.app')

@title('Персональные бонусы')

@className('main_infopage')

@section('content')
	<div class="content">
		<div class="infopage infopage_bonuses">
			<div class="infopage__title-wrap">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<h1 class="infopage-title">Персональные бонусы и предложения</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="infopage__content">
						<div class="infopage-block infopage-block_brief corner-bottom">
							<h2 class="infopage-block__title">Дарим приятные бонусы. Просто так!</h2>
							<div class="infopage-block__text">
								<p>Сервис CRYPTOLIDE очень любит своих пользователей и постоянно стремится к тому, что бы и пользователи чувствовали себя незаменимой частичкой нашей большой команды. Именно поэтому был разработан специальный алгоритм, который анализирует действия каждого участника сервиса и на основе полученных данных формирует и совершенно бесплатно предоставляет как раз те бонусы и акционные предложения, которые действительно будут интересны конкретному пользователю. Например, для активных трейдеров сервис предлагает дополнительное отключение комиссии, расширенный функционал, индивидуальные условия отображения объявлений и множество других инструментов, которые значительно улучшат торговлю и взаимодействие с другими участниками сервиса. Для пользователей, которые занимаются привлечением партнёров в команду, сервис дарит временное увеличение партнёрской ставки, сертификаты на зачисление в команду тех пользователей, которые были зарегистрированы без пригласителя, создание уникальных лендингов и других рекламных материалов, а так же массу других дополнительных возможностей, которые отлично помогают совершить задуманное. Мы понимаем, что каждый пользователь - уникален и поэтому стараемся создать такие условия взаимодействия с сервисом, при которых каждый будет чувствовать себя особенным! <br><br>Помните, что именно в CRYPTOLIDE вы всегда получаете больше!
								</p>
							</div>							
						</div>
						<div class="infopage-block infopage-block_bonuses corner-top">
							<div class="buttons">
								<a href="/mybonuses" class="btn-green3 buttons__btn buttons__btn_view-bonuses" target="_blank">Посмотреть мои бонусы</a>
								<span class="buttons__sep">или</span>
								<a href="#" class="buttons__btn btn-blue2" onclick="Chatra('openChat', true); return false;">Задать вопрос оператору</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
@endsection